### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by SheepTester** [Gamepro5/gamepro5.github.io#1]
Times new roman is overused; I'd suggest [Roboto](https://fonts.google.com/specimen/Roboto) or [Open Sans](https://fonts.google.com/specimen/Open+Sans) if you like sans serif fonts.

**Comment by Gamepro5** [comment]
sorry! I dont know how to change it! I tried changing it to "Fredoka One" and some other text to  "Comic Sans". Please make a video tutorial on how and how to upload a website

**Comment by SheepTester** [comment]
Firstly, please avoid using Comic Sans as it has a bad reputation.

Secondly, you can either edit a file directly on the website and then commit the change. Refer to figures 1-3 for details.

![opening a file](https://cloud.githubusercontent.com/assets/22133785/25882211/b298f794-34f6-11e7-9573-1e9751c64ee6.png)
_Fig 1: Opening a file on the Github website._

![clicking edit button](https://cloud.githubusercontent.com/assets/22133785/25882229/e26088fc-34f6-11e7-929f-26b59dc0a1a4.png)
_Fig 2: Opening the file editor_

![saving changes](https://cloud.githubusercontent.com/assets/22133785/25882269/2858147e-34f7-11e7-8e65-a98c82a7198c.png)
_Fig 3: Committing changes_

**Comment by SheepTester** [comment]
Alternatively, you can edit the file on your computer, then go to the Github desktop app, commit changes and sync. Refer to figures 4-5.

![committing changes](https://cloud.githubusercontent.com/assets/22133785/25882327/a5173576-34f7-11e7-8edb-1f47feac48a7.png)
_Fig 4: Committing changes on the Github desktop app_

![syncing](https://cloud.githubusercontent.com/assets/22133785/25882352/d9088894-34f7-11e7-8d2c-453b50b457cb.png)
_Fig 5: Syncing commits_
