### ISSUE TITLE
how to make a new alert

### ISSUE THREAD

**Issue by SheepTester** [Gamepro5/gamepro5.github.io#28]
you need to come up with a unique name for your alert. it can only consist of lowercase letters (not really -- but I'm too lazy to explain all the rules to you and you aren't intelligent enough to comprehend it anyways)

do the following in your [`index.html`](https://github.com/Gamepro5/gamepro5.github.io/blob/master/index.html):

copy and paste this after the other alerts:
```html
<center>
  <div class="alert" style="width:280px;" id="NAME"> 
    <span class="closebtn" onclick="this.parentElement.style.display='none';localStorage.NAME='yes';">&times;</span> 
    <br>TITLE<br>
    CONTENT
    <p>
      <a class="popupbutton" href=programs/gamepro5_game.html>BUTTON</a>
    </p>
  </div>
</center>
```
replace the `NAME`s with the unique name you came up with, and fill in `TITLE`, `CONTENT`, and `BUTTON`

in your `<script>` tag, copy and paste this after the others:
```js
t=document.querySelector('#NAME');
if (localStorage.NAME==='yes') t.style.display='none';
```
replace the `NAME`s with the unique name you came up with

assuming you were smart enough to understand the above, you should experience no problems 👍

**Comment by Gamepro5** [comment]
gee thanks; "i'm not intelligent enough"

**Comment by SheepTester** [comment]
don't want to overestimated your intelligence
